networks:
  dev:
    name: dev_network
    driver: bridge

services:
  postgres:
    restart: always
    networks:
      - dev
    build: .
    image: my-student-image
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -h localhost -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
